### ISSUE TITLE
Make the default keys file $HOME/.switch/prod.keys

### ISSUE THREAD

**Issue by friedkeenan** [The-4n/hacBrewPack#11]
This would keep it in line with hactool's, Lockpick's, and Atmosphere's standard

**Comment by The-4n** [comment]
Placing keys in that path causes more trouble, Specially for windows user
Also keys get outdated and people forget about it

**Comment by friedkeenan** [comment]
Could you expand on how that path causes more trouble? Hactool's releases are for Windows, so I don't see why that path couldn't be used here.

Also, it's not like you dump your keys every time you use this, so I don't see how people forgetting about outdated keys would be more of a problem with that path.

**Comment by The-4n** [comment]
After some new major firmwares, I'll get flooed by: "Hey, when i create my homebrew with keygen x it doesn't install on switch" cause they usually forget they need to provide keys for that keygen
and implementing some key checking function requires a program update for every new keygen

Placing keys file near program or passing them with -k is not a big deal

**Comment by shchmue** [comment]
how would it require a program update? just check the key area key at the index specified by the key generation in the nca header against the zero vector (hactool itself does similar in pki to make sure key sources exist before using them) and if it's missing, tell users it's missing master_key_xx corresponding to that index

**Comment by The-4n** [comment]
I may add it in future, of course keys.dat will remain as main keyset file, but I'll consider loading keys from other locations of keys.dat is not found

**Comment by The-4n** [comment]
Ok guys, many years passed since this issue is created, and it's time to resolve it
