### ISSUE TITLE
Fails to create NSP from 10 second run returns control.nacp

### ISSUE THREAD

**Issue by teamxecuter** [The-4n/hacBrewPack#8]
I don't think the file can be shared here, so I won't upload it.
The error I get when trying to use the control.nacp:

```
hacBrewPack v1.15 by The-4n

Removing existing temp and nca directories
Creating temp, nca and nsp directories

----> Process NACP
Validating Title Name
Error: Invalid Title Name in control.nacp
```

The files in the control folder:
icon_Japanese.dat
control.nacp

I'm gonna assume that, if you use the same NACP verification in hacPack, it also won't work using that.

**Comment by The-4n** [comment]
well it seems your game/app is Japanese only
I'll fix it in hacPack, not sure for hackBrewPack

**Comment by The-4n** [comment]
what title are you repacking?
